Update epg-workflow.yml

diff --git a/.github/workflows/epg-workflow.yml b/.github/workflows/epg-workflow.yml
--- a/.github/workflows/epg-workflow.yml
+++ b/.github/workflows/epg-workflow.yml
@@ -33,8 +33,14 @@ jobs:
       - name: Run the initial EPG processing script
         run: python .github/workflows/process_epg_initial.py
 
+      - name: Verify EPGcompleto.xml exists
+        run: ls -l /tmp/epg/EPGcompleto.xml
+
       - name: Run the final EPG processing script
         run: python .github/workflows/process_epg_final.py
+
+      - name: Verify EPGcompleto.xml exists after final processing
+        run: ls -l /tmp/epg/EPGcompleto.xml
 
       - name: Commit and push updated EPGcompleto.xml
         env:
@@ -43,11 +49,15 @@ jobs:
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
           
-          # Reemplazar el archivo EPGcompleto.xml en el repositorio
-          cp /tmp/epg/EPGcompleto.xml ./EPGcompleto.xml
-          
-          # Añadir y hacer commit del archivo actualizado
-          git add EPGcompleto.xml
-          git commit -m "Update EPGcompleto.xml"
-          git push origin main
+          # Verifica si el archivo existe antes de copiarlo
+          if [ -f /tmp/epg/EPGcompleto.xml ]; then
+            cp /tmp/epg/EPGcompleto.xml ./EPGcompleto.xml
+            git add EPGcompleto.xml
+            git commit -m "Update EPGcompleto.xml"
+            git push origin main
+          else
+            echo "EPGcompleto.xml not found in /tmp/epg/"
+            exit 1
+          fi
+
 
